# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=140)),
                ('Autor', models.CharField(max_length=200)),
                ('Editorial', models.CharField(max_length=400)),
                ('ISBN', models.CharField(max_length=250)),
                ('Precio', models.FloatField()),
                ('Creacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
